# -----------------
# built on dom with: 
#   buildah bud --volume $PWD/SPH-EXA.git:/usr/local/games/SPH-EXA.git \
#   --format=docker -f Dockerfile_install \
#   --tag sph-exa_install:cuda_debug-gpud .
#
# CMAKE_BUILD_TYPE=Debug + GPU_DIRECT=OFF       sph-exa_install:cuda_debug-gpud
# CMAKE_BUILD_TYPE=Release + GPU_DIRECT=OFF     sph-exa_install:cuda_release-gpud
# CMAKE_BUILD_TYPE=Debug + GPU_DIRECT=ON        sph-exa_install:cuda_debug_plus_gpud
# CMAKE_BUILD_TYPE=Release + GPU_DIRECT=ON      sph-exa_install:cuda_release_plus_gpud
# buildah push sph-exa_install:cuda docker://art.cscs.ch/contbuild/testing/jg/sph-exa_install:cuda
#
# ART=docker://art.cscs.ch/contbuild/testing/jg/sph-exa_install
# buildah push localhost/sph-exa_install:cuda_release_plus_gpud $ART:cuda_release_plus_gpud    
# buildah push localhost/sph-exa_install:cuda_debug_plus_gpud   $ART:cuda_debug_plus_gpud   
# buildah push localhost/sph-exa_install:cuda_release-gpud      $ART:cuda_release-gpud     
# buildah push localhost/sph-exa_install:cuda_debug-gpud        $ART:cuda_debug-gpud
# -----------------
# mac:~/readme.containers
FROM art.cscs.ch/contbuild/testing/jg/sph-exa_base:cuda
# FROM localhost/local:cuda
# base depends on: FROM nvidia/cuda:11.7.0-base-ubuntu20.04

# sed -i "s@GIT_REPOSITORY@SOURCE_DIR /usr/local/games/googletest-release-1.11.0/\n#@" ./domain/cmake/setup_GTest.cmake
# sed -i "s@GIT_REPOSITORY@SOURCE_DIR /usr/local/games/googletest-release-1.11.0/\n#@" ./cmake/setup_GTest.cmake
# sed -i "s@GIT_REPOSITORY@SOURCE_DIR /usr/local/games/googletest-release-1.11.0/\n#@" ./ryoanji/cmake/setup_GTest.cmake
# sed -i "s@GIT_TAG@#GIT_TAG @" ./domain/cmake/setup_GTest.cmake
# sed -i "s@GIT_TAG@#GIT_TAG @" ./cmake/setup_GTest.cmake
# sed -i "s@GIT_TAG@#GIT_TAG @" ./ryoanji/cmake/setup_GTest.cmake

ENV TZ Europe/Zurich
ENV PATH="${PATH}:/usr/local/cuda/bin"
ENV CMAKE_PREFIX_PATH="/usr/local/HDF_Group/HDF5/1.13.0/share/cmake:${CMAKE_PREFIX_PATH}"

#del #{{{ cmake:
#del RUN echo \
#del     && echo "## cmake-3.22.2:" \
#del     && cd /usr/local/games \
#del     && tar xf cmake-3.22.2-linux-x86_64.tar.gz \
#del     && cp -a cmake-3.22.2-linux-x86_64/bin/* /usr/bin/ \
#del     && cp -a cmake-3.22.2-linux-x86_64/share/cmake-3.22 /usr/share/cmake-3.22 \
#del     && rm -fr cmake-3.22.2-linux-x86_64.tar.gz cmake-3.22.2-linux-x86_64/bin/cmake-gui
#del #}}}

# export CMAKE_PREFIX_PATH=/usr/local/HDF_Group/HDF5/1.13.0/share/cmake:$CMAKE_PREFIX_PATH
#{{{ sphexa:cuda
## debug with: 
#    buildah rm deleteme
#    buildah from --name deleteme aa3d015969d4
#    buildah run -t deleteme bash
#    buildah tag 8a2921008544 local:cuda # -> FROM localhost/local:cuda
#    buildah push localhost/local:cuda  docker://art.cscs.ch/contbuild/testing/jg/sph-exa_base:cuda
RUN echo \
    && echo "## sphexa:cuda" \
    && date \
    && which nvcc \
    && cd /usr/local/games \
    && export CMAKE_PREFIX_PATH=/usr/local/HDF_Group/HDF5/1.13.0/share/cmake:$CMAKE_PREFIX_PATH \
    && cmake -S SPH-EXA.git -B build \
    -DCMAKE_CXX_COMPILER=mpicxx \
    -DCMAKE_C_COMPILER=mpicc \
    -DGPU_DIRECT=ON \
    -DCMAKE_BUILD_TYPE=Release \
    && echo \
    && cmake --build build -j -t install

#     -DGPU_DIRECT=OFF \
#     -DCMAKE_BUILD_TYPE=Debug \
#     #
#     -DGPU_DIRECT=OFF \
#     -DCMAKE_BUILD_TYPE=Release \
#     #
#     -DGPU_DIRECT=ON \
#     -DCMAKE_BUILD_TYPE=Debug \
#     #
#     -DGPU_DIRECT=ON \
#     -DCMAKE_BUILD_TYPE=Release \
#}}}

#del #{{{ test with:
#del #{{{ -> installed:
#del # -- Installing: /usr/local/sbin/coord_samples/coordinate_test
#del # -- Installing: /usr/local/sbin/integration_mpi/globaloctree
#del # -- Installing: /usr/local/sbin/integration_mpi/exchange_halos
#del # -- Installing: /usr/local/sbin/integration_mpi/box_mpi
#del # -- Installing: /usr/local/sbin/integration_mpi/exchange_focus
#del # -- Installing: /usr/local/sbin/integration_mpi/exchange_keys
#del # -- Installing: /usr/local/sbin/integration_mpi/focus_transfer
#del # -- Installing: /usr/local/sbin/integration_mpi/domain_2ranks
#del # -- Installing: /usr/local/sbin/integration_mpi/treedomain
#del # -- Installing: /usr/local/sbin/integration_mpi/exchange_general
#del # -- Installing: /usr/local/sbin/integration_mpi/exchange_domain
#del # -- Installing: /usr/local/sbin/integration_mpi/focus_tree
#del # -- Installing: /usr/local/sbin/integration_mpi/domain_nranks
#del # -- Installing: /usr/local/sbin/integration_mpi/exchange_halos_gpu
#del # -- Installing: /usr/local/sbin/performance/octree_perf
#del # -- Installing: /usr/local/sbin/performance/peers_perf
#del # -- Installing: /usr/local/sbin/performance/scan_perf
#del # -- Installing: /usr/local/sbin/performance/hilbert_perf
#del # -- Installing: /usr/local/sbin/performance/cudaNeighborsTest
#del # -- Installing: /usr/local/sbin/performance/octree_perf_gpu
#del # -- Installing: /usr/local/sbin/performance/hilbert_perf_gpu
#del # -- Installing: /usr/local/sbin/unit/component_units
#del # -- Installing: /usr/local/sbin/unit/component_units_omp
#del # -- Installing: /usr/local/sbin/unit_cuda/component_units_cuda
#del # -- Installing: /usr/local/sbin/ryoanji/ryoanji_demo/ryoanji_demo
#del # -- Installing: /usr/local/sbin/ryoanji/cpu_unit_tests/ryoanji_cpu_unit_tests
#del # -- Installing: /usr/local/sbin/ryoanji/unit_tests/ryoanji_unit_tests
#del # -- Installing: /usr/local/sbin/ryoanji/global_upsweep_cpu
#del # -- Installing: /usr/local/sbin/ryoanji/global_upsweep_gpu
#del # -- Installing: /usr/local/sbin/hydro/kernel_tests_std
#del # -- Installing: /usr/local/sbin/hydro/kernel_tests_ve
#del # -- Installing: /usr/local/bin/sphexa
#del # -- Installing: /usr/local/bin/sphexa-cuda
#del # -- Installing: /usr/local/bin/sedov_solution
#del # -- Installing: /usr/local/bin/compare_solutions.py
#del # -- Installing: /usr/local/bin/compare_noh.py
#del #}}}
#del #}}}
